// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGhHb6_FEdbUCnUuXc-rQzow4RmIH2AC8',
    appId: '1:963069320965:web:64b82b475e639d4119616c',
    messagingSenderId: '963069320965',
    projectId: 'moyemoye-2ca6e',
    authDomain: 'moyemoye-2ca6e.firebaseapp.com',
    storageBucket: 'moyemoye-2ca6e.appspot.com',
    measurementId: 'G-F97N1NNLKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGcnKOU1QyAhjcGwjd8Aa1H9rF8gz_56c',
    appId: '1:963069320965:android:09f147bfc85db1a319616c',
    messagingSenderId: '963069320965',
    projectId: 'moyemoye-2ca6e',
    storageBucket: 'moyemoye-2ca6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BFK1omKtaX29fKIDXJGawZhcUAOGJCU',
    appId: '1:963069320965:ios:0f8be9423509e42319616c',
    messagingSenderId: '963069320965',
    projectId: 'moyemoye-2ca6e',
    storageBucket: 'moyemoye-2ca6e.appspot.com',
    iosBundleId: 'com.example.moyemoye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1BFK1omKtaX29fKIDXJGawZhcUAOGJCU',
    appId: '1:963069320965:ios:fa554a4c34314d7f19616c',
    messagingSenderId: '963069320965',
    projectId: 'moyemoye-2ca6e',
    storageBucket: 'moyemoye-2ca6e.appspot.com',
    iosBundleId: 'com.example.moyemoye.RunnerTests',
  );
}
